version: "3.2"

services:
 
  ${SERVICE_NAME}:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME-$TAG}
    networks:
      - apps
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      replicas: ${SCALABLE_REPLICAS}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==worker
      labels:
        - "traefik.enable=true"
        - "traefik.tags=public"
        - "traefik.http.routers.${SERVICE_NAME}.rule=${DOMAINS}"
        - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${TARGET_PORT}"
        - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
        - "traefik.http.routers.${SERVICE_NAME}.service=${SERVICE_NAME}"
        - "traefik.docker.network=traefik2_apps"

networks:
  apps:
    external:
      name: traefik2_apps
