version: "3.2"

services:
  ui:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME-$CAL_VER}
    networks:
      apps:
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      mode: replicated
      replicas: ${SERVICE_MIN_REPLICAS:-1}
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role==worker
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 64M
      labels:
        - "traefik.backend=cmp-ui"
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_apps"
        - "traefik.frontend.rule=Host:${HOST}"
networks:
  apps:
    external:
      name: traefik_apps
