version: '3'

services:

  hydra-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=cockroach://root@127.0.0.1:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure

  hydra:
    depends_on:
      - hydra-migrate
    environment:
      - DSN=cockroach://root@127.0.0.1:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGIN=http://127.0.0.1:3000/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
    command:
      serve all --dangerous-force-http
    restart: unless-stopped
    
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v1.0.0-rc.10
    ports:
      - "3000:3000"
    restart: unless-stopped

  cockroachd:
    image: cockroachdb/cockroach:v2.1.6
    ports:
      - "26257:26257"
    command: start --insecure