export const moduleName = {
  billingModule: 'BillingModule',
  pricingModule: 'PricingModule',
  updateBillingModule: 'UpdateBillingModule',
  cookieBannerModule: 'CookieBannerModule',
  setUpModule: 'SetUpModule',
  cookieCategoryModule: 'CookieCategoryModule',
  cookieTrackingModule: 'CookieTrackingModule',
  cookieConsentModule: 'CookieConsentModule',
  ccpaDsarModule: 'CcpaDsarModule',
  webFormModule: 'WebFormModule',
  workFlowModule: 'WorkflowModule',
  dsarWebFormModule: 'DSARWebFormModule',
  dsarRequestModule: 'DSARRequestModule',
  editProfileModule: 'EditProfileModule',
  companyModule: 'CompanyModule',
  companyTeamModule: 'CompanyTeamModule',
  verifyEmailModule: 'VerifyEmailModule',
  loginModule: 'LoginModule',
  resetPasswordModule: 'ResetPasswordModule',
  registerModule: 'RegisterModule',
  organizationTeamModule: 'OrganizationTeamModule',
  organizationDetailsModule: 'OrganizationDetailsModule',
  headerModule: 'HeaderModule',
  forgotPasswordModule: 'ForgotPasswordModule'

};
